### ISSUE TITLE
Recover signer

### ISSUE THREAD

**Issue by jetaggart** [airalab/hs-web3#109]
How would I recover the signer from a signed message as seen here: https://ethereum.stackexchange.com/questions/2660/how-can-i-verify-a-signature-with-the-web3-javascript-api?

Is this possible with this lib locally or do I have to run this through a node as seen here: https://github.com/airalab/hs-web3/blob/e6719ae384d2371a342f03afa3634921f4a8cd37/packages/ethereum/src/Network/Ethereum/Api/Personal.hs#L91-L93?

The reason I ask is I'm using infura as my provider and it doesn't support this function, as expected: `CallException JSON-RPC error -32601: The method personal_ecRecover does not exist/is not available. Data: Nothing`

**Comment by akru** [comment]
Hello, unfortunately ECDSA recover function isn’t implemented yet, in future it could be located in https://github.com/airalab/hs-web3/blob/master/packages/crypto/src/Crypto/Ecdsa/Signature.hs

According to your example, I’m not sure that Ethereum node exports personal_ecRecover method.

As temporary workaround you could deploy or use already existed smart contract with ecRecover method.

**Comment by psylinse** [comment]
Okay thanks, wanted to make sure I wasn't missing something. I don't have the cryptographic chops to write that function unfortunately or I'd take a stab. 

You're right, I doubt any nodes export that function, it doesn't make sense.

Thanks for the workaround, that's a great idea!

**Comment by psylinse** [comment]
In case anyone is wondering how to do this with @akru's suggestion, this is what I came up with. I deployed this smart contract:

```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";


contract Security {
    function isValidSignature(address signer, bytes32 hash, bytes memory signature) public view returns (bool) {
        return SignatureChecker.isValidSignatureNow(signer, ECDSA.toEthSignedMessageHash(hash), signature);
    }
}
```

I signed a message in the client via web3:

```
web3.eth.personal.sign(web3.utils.sha3("MESSAGE TO SIGN"), "0xACCOUNT TO SIGN")
```

Then validated the signer is correct on the backend via the smart contract:

```
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE DeriveGeneric         #-}
{-# LANGUAGE FlexibleContexts      #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}

import qualified Data.ByteArray.Sized as SBA
import           Crypto.Ecdsa.Utils
import           Crypto.Hash
import           Network.Web3
import           Network.Ethereum
import           Network.Ethereum.Account
import qualified Network.Ethereum.Api.Personal   as Eth
import           Network.Web3.Provider
import           Data.ByteArray.HexString   (HexString, toBytes)
import           Data.Solidity.Prim
import           Data.Solidity.Abi.Codec

data SignInRequest = SignInRequest
    { signer :: Address
    , sig :: HexString
    }
    deriving (Show, Generic)
instance FromJSON SignInRequest
instance ToJSON SignInRequest

// uses cryptonite
hexSha3_256 :: ByteString -> String
hexSha3_256 bs = "0x" ++ show (hash bs :: Digest Keccak_256)

[abiFrom|Security.json|]

main = do
  isValidSig <- runWeb3' (HttpProvider "https://ropsten.infura.io/v3/INFURA_KEY") $ do
    withAccount () $
        withParam (to .~ "SMART CONTRACT ADDRESS") $ do
            let hash = SBA.unsafeSizedByteArray . fromString $ hexSha3_256 (BC.pack ("MESSAGE TO SIGN" :: String))
            isValidSignature (signer req) hash (toBytes $ sig req)
  putStrLn $ show isValidSig
```

I'm not 100% on the security of this, so use it as a jumping off point. I struggled with this so probably some simplifications that can be made. Any feedback is appreciated!

**Comment by akru** [comment]
Thank you @psylinse! Feel free to enhance hs-web3 docs: https://hs-web3.readthedocs.io
Your samples look like a good section of the troubleshooting page.
