### ISSUE TITLE
Releasing on Hackage or adding .cabal files to the repo?

### ISSUE THREAD

**Issue by gromakovsky** [airalab/hs-web3#112]
We are using packages from this repo as dependencies in one project that we build with `stack`. It produces a lot of such messages:
```
DEPRECATED: The package at Repo from https://github.com/serokell/hs-web3.git, commit b0033e59520e063f38c0691ff789002e2b97ccb2 in subdir packages/hexstring does not include a cabal file.
Instead, it includes an hpack package.yaml file for generating a cabal file.
This usage is deprecated; please see https://github.com/commercialhaskell/stack/issues/5210.
Support for this workflow will be removed in the future.
```

Currently it works, but as you can see this workflow is deprecated and will be removed in the future.
Also AFAIU the new version of this package (which is now split into many packages) is no longer on Hackage, so the only possible way to use it is as a git dependency with all these verbose messages.

So I wonder whether you plan to add `.cabal` files to the repo (to make it more usable as a git dependency in Stack) or upload all new packages to Hackage.

**Comment by akru** [comment]
Hi, @gromakovsky I hope to publish the 1.0 release into Hackage already split to many packages when the functionality of web3-polkadot package will be stabilized (est. September).

Using git version is very usefull I guess, feel free for open PR that enables that functionality.

**Comment by domenkozar** [comment]
I'm currently planning to vendor-in web3-jsonrpc (that's weird name since it's not specific to web3), are there still plans to release it to hackage?

**Comment by domenkozar** [comment]
I've released it under [jsonrpc-tinyclient ](https://hackage.haskell.org/package/jsonrpc-tinyclient), I'm happy to transfer maintenance or delete it once you're ready on your side.

**Comment by akru** [comment]
Hello @domenkozar, glad to see you here!

So, the name decided to have `web3` prefix just because it’s part of Haskell Web3 library. But your proposal is better, I’m agree. I’ll be happy if you will maintain it and support release process. I’ll change package name here to suits your hackage location.

I’ll continue development on this repository, is it ok?

**Comment by domenkozar** [comment]
Hey @akru thanks!

At the end I didn't decide to use jsonrpc, because the client is of synchronous nature and I need async support in order to not miss any messages.

Going with a custom protocol was easier :)

Maybe I regret that and help turn it into something a bit more generic.

**Comment by akru** [comment]
I see, no problem @domenkozar

**Comment by gromakovsky** [comment]
@akru do you still plan to release packages to Hackage? If yes, do you have a new estimate for that?

**Comment by akru** [comment]
Great, thank you for remind me @gromakovsky! I’ll do it on winter holidays if no issues on the way. In that case estimation is January 2022.

**Comment by kk-hainq** [comment]
This is also a core dependency of our project, thanks! 

We would love to have it on Hackage or add the cabal files, and are willing to contribute in any way to achieve it!

**Comment by akru** [comment]
Hi @kk-hainq, glad to see you, project uploaded to Hackage! 
@gromakovsky https://hackage.haskell.org/package/web3-1.0.0.0
I'll happy to see your bug reports or any other contribution!

@domenkozar could you release `jsonrpc-tinyclient` package name please, or feel free to maintain it if you wish.

**Comment by kk-hainq** [comment]
@akru Awesome, thank you! Also, will it be possible to get the rest of the packages (`web3-hexstring` and friends) to Hackage?

**Comment by akru** [comment]
@kk-hainq other packages also published, just look to some renames like `web3-hexstring -> memory-hexstring` and `web3-jsonrpc -> jsonrpc-tinyclient`.
