### ISSUE TITLE
Inifinite loop in Network.Ethereum.Account.getReceipt

### ISSUE THREAD

**Issue by pkozakowski** [airalab/hs-web3#120]
In the current implementation of `Network.Ethereum.Account.send`, the call blocks until the transaction goes through or reverts. This is done using `getReceipt`, which queries the node for the status of the transaction in an infinite loop.

That's a problem if the gas price was underestimated - then the call blocks indefinitely. I'm currently having this issue on Polygon. I would like to be able to bump up the gas price if the transaction was pending for some time.

Two possible solutions come to my mind:

1. Remove the blocking `getReceipt` call from `send` and move the responsibility for waiting on the transaction to the user. Probably the cleanest solution, but complicating the most common use-case a little bit.
2. Add a timeout parameter to `send`, set e.g. by `withParam`.

I'd be happy to implement either way.

Also, thanks a lot for this awesome library! I started using it in one of my projects and it's been great so far.

**Comment by akru** [comment]
Thank you @pkozakowski for your report! 
Yes, loop is not that we want to have in our code, right. Feel free to share your ideas how can we escape it. May be some timeouts?

**Comment by akru** [comment]
What’s about to use IO wait helpers code from threading libraries? It’s already implements blocking IO wait logic.

**Comment by pkozakowski** [comment]
There's also [`timeout`](https://hackage.haskell.org/package/base-4.16.0.0/docs/src/System.Timeout.html#timeout) which does the same thing but abstracts out threads. How about this plan:

1. Add field `_timeout :: Maybe Integer` to [`CallParam`](https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Account/Internal.hs#L42) specifying the timeout in seconds or miliseconds, allow setting using [`withParam`](https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Account/Internal.hs#L98). `Nothing` means waiting forever.
2. Change [`getReceipt`](https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Account/Internal.hs#L118) to accept the timeout parameter and return `Maybe TxReceipt`, which will be `Nothing` if we hit the timeout before the transaction goes through.
3. Change the return types of [`send`](https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Account/Class.hs#L43) and functions derived by [`abi`](https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Contract/TH.hs#L92) accordingly. Alternatively we could throw an IO exception in case of a timeout and leave the return types as they are, not sure which one is better.

What do you think?

**Comment by akru** [comment]
Good plan, let's extend our state by `timeout` parameter. We probably don't need `timeout` functions, argument to `getReceipt` works well. Just user recursive decrement for this parameter on each `getReceipt` iteration.

One funny thing is we already have TODO for this bug few years ago:

https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Account/Internal.hs#L125

**Comment by pkozakowski** [comment]
Sent a PR, see above. Sorry it took so long.
