### ISSUE TITLE
Module re-organization

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#14]
From the point of view of Haskell, many RPC functions have non-standard names. I propose that these non-standard functions, e.g. `eth_blockNumber`, be placed in an `Internal` module and be made available to users of the library via an `Eth` module thus: `Eth.blockNumber`.

**Comment by akru** [comment]
I'm fully support this proposal, but keep in mind that currently `Interal` module contains two functions (`toLowerFirst`, `toUpperFirst`) that used in template system and imported in many places.

**Comment by akru** [comment]
So, as I can see, you proposal is renaming `Network.Ethereum.Web3.{Api ->Eth}` with `eth_` reduction. But `Api` module also contains `web3_` prefixes, and will contains `shh_` in the future. What do you think about it?

**Comment by aupiff** [comment]
I was thinking that we'd make three new modules: `Network.Ethereum.Web3.Eth`, `Network.Ethereum.Web3.Web3` and `Network.Ethereum.Web3.Shh`.

**Comment by akru** [comment]
Good, could you prepare PR with changes?

**Comment by aupiff** [comment]
Yep, I'll finish this today.

**Comment by aupiff** [comment]
@akru can you merge #13 before I make these module changes so I have all the rpc methods available to reorganize.

**Comment by akru** [comment]
Oh, you are right, merged.
