### ISSUE TITLE
Alchemy JSON RPC Update according to Ethereum Spec

### ISSUE THREAD

**Issue by charlescrain** [airalab/hs-web3#141]
[Ethereum is deprecating totalDifficult](https://github.com/ethereum/execution-apis/pull/570) and we should prepare accordingly.

The change would be here:
https://github.com/airalab/hs-web3/blob/master/packages/ethereum/src/Network/Ethereum/Api/Types.hs#L282

for backwards compatibility, we can just make a Maybe:

```
, blockTotalDifficulty  :: !(Maybe Quantity)
```

**Comment by charlescrain** [comment]
Here's the pull request: https://github.com/airalab/hs-web3/pull/142

**Comment by akru** [comment]
Cool, merged!
