### ISSUE TITLE
Fix intermittent Travis failures.

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#16]
Haven't investigated the cause yet, but Travis fails intermittently while building `web3`...

```
Configuring web3-0.5.5.0...
cabal: Encountered missing dependencies:
aeson -any,
attoparsec -any,
base16-bytestring -any,
cryptonite -any,
http-client -any,
http-client-tls -any,
memory -any,
text -any,
vector -any
```

**Comment by akru** [comment]
Latest builds with TravisCI is ok https://travis-ci.org/airalab/hs-web3/jobs/292758033
Looks like temporary problem on TravisCI side.

**Comment by aupiff** [comment]
@akru could you please reopen this issue?
