### ISSUE TITLE
resolve bugs with non-array [`bytes1`...`bytes32`] types.

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#17]
Any types `bytes1` ... `bytes32` in an an abi currently cause an error to be thrown. These types are neither static nor dynamic bytes arrays (both of which are currently supported), and thus must have new types created from them, along with `ABIEncoding`, `Show`, and `EncodingType` instances.

I've started this work [in a branch in my forked repo](https://github.com/aupiff/hs-web3/tree/fix-abi). I'll submit a PR once I've done a bit of testing.

An example of a solidity function's abi which would fail to parse:

```
  {
    "constant": false,
    "inputs": [
      {
        "name": "_ucacId",
        "type": "bytes32"
      }
    ],
    "name": "executeUcacTx",
    "outputs": [],
    "payable": false,
    "type": "function"
  }
```

**Comment by aupiff** [comment]
I've looked at this issue again and I think now that the `BytesN` type is OK, it is just improperly implemented. We probably won't have to create new types. I'll work on this tomorrow.

**Comment by akru** [comment]
For type `BytesN` I use [type level literals](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/type-level-literals.html) approach, `DataKinds` extension should be enabled:

```haskell
{-# LANGUAGE DataKinds #-}
```

**Comment by aupiff** [comment]
Ah, of course! My mistake. Thank you.
