### ISSUE TITLE
Make `_call` and `_sendTransaction` configurable using an argument of type `Call`

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#24]
I suggest that both the `_call` and `_sendTransaction` functions of `Contract.hs` should take a `Call` as an argument as opposed to the current scheme of taking an `Address` and `Unit`:

```
_sendTransaction :: (Provider p, Method a, Unit b)
                 => Address -> b -> a -> Web3 p TxHash
_sendTransaction to value dat = do
    primeAddress <- listToMaybe <$> eth_accounts
    eth_sendTransaction (txdata primeAddress $ Just $ toData dat)
  where txdata from = Call from to (Just defaultGas) Nothing (Just $ toWeiText value)
        toWeiText   = ("0x" <>) . toStrict . B.toLazyText . B.hexadecimal . toWei
        defaultGas  = "0x2DC2DC"
```

We should eventually change the types of the fields of the `Call` type to be more descriptive, but that will be done in a future PR. All the fields of the `Call` type are useful in the `_sendTransaction` function. Passing in this type will allow for the configuration of the `from` and `gas` fields which are currently set automatically.

```
-- | The contract call params
data Call = Call
  { callFrom    :: !(Maybe Address)
  , callTo      :: !Address
  , callGas     :: !(Maybe Text)
  , callGasPrice:: !(Maybe Text)
  , callValue   :: !(Maybe Text)
  , callData    :: !(Maybe Text)
  } deriving Show
```

I also propose creating a `Data.Default` instance for the `Call` type so that invoking `_sendTransaction` is less of a hassle.

**Comment by akru** [comment]
So, it's interested case, as I can see your proposal is, for example

```haskell
_sendTransaction to value method
```

to

```haskell
_sendTransaction (def { callTo = to, callValue = value, callData = method })
```

I'm agree with you, but in this case `Call` fields should be more representative.

**Comment by aupiff** [comment]
@akru, you're right. I'll improve the types of `Call`'s fields and then make this change.
