### ISSUE TITLE
ABIEncoding instance incorrect for tuples.

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#25]
The `toDataBuilder` method in the `AbiEncoding` instance for tuples in incorrect. It's difficult to explain why in words, but I can try based on particular questions. The problem is in how you are calculating the offset. you can see the example [here](https://github.com/f-o-a-m/purescript-web3/blob/master/test/Web3Spec/Encoding/Containers.purs#L107) in our purescript-web3 tests for which yours will fail, and this is backed up by the web3-js results

Please refer to the [official documentation](http://solidity.readthedocs.io/en/develop/abi-spec.html#formal-specification-of-the-encoding) and compare your instance to the [purescript web3 instance](https://github.com/f-o-a-m/purescript-web3/blob/master/src/Network/Ethereum/Web3/Solidity/Tuple.purs#L34).

**Comment by akru** [comment]
Thank you for reporting! I’ll check it as soon as possible.
