### ISSUE TITLE
ABIEncoding incorrect for static arrays

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#26]
The following `ABIEncoding` may work for dynamic arrays, but it is incorrect for static arrays with the type `bytes32[3]`, for example. These arrays do not use length parameters.

```haskell                                                                                                                                                  
 67 instance ABIEncoding a => ABIEncoding [a] where                                                                                                                                                        
 68     toDataBuilder x = int256HexBuilder (length x)                                                                                                                                                  
 69                       <> foldMap toDataBuilder x                                                                                                                                       
 70     fromDataParser = do len <- int256HexParser                                                                                                                                                    
 71                         take len <$> P.many1 fromDataParser
```

If I call a function with the following signature, I don't observe any length arguments in the `calldata` field of the transaction:
```
function issueCredit( bytes32 ucac, address creditor, address debtor, uint256 amount, bytes32[3] memory sig1, bytes32[3] memory sig2, bytes32 memo) public {
```

observed `calldata`:
```
0xcada9c457624778dedc75f8b322b9fa1632a610d40b85e106c7d9bf0e743a9ce291b9c6f0000000000000000000000006a362e5cee1cf5a5408ff1e12b0bc546618dffcb00000000000000000000000011edd217a875063583dd1b638d16810c5d34d54b000000000000000000000000000000000000000000000000000000000000000a819df6d812858e093b28f001e5d85527cf72dcc2c5ba478bb78ca73ef96449f92f0865223bb54e0b8d7fdcccc0e4cc9bb63cb65259502d7f6c6fbcfb82cb485b000000000000000000000000000000000000000000000000000000000000001c49646eb7175d4ff98ddd7fc1005524a9cd05112dac59bde16e82c46352572f414ef1fb12538003b0f0c7f816c0334fd986ad12419b2b911f2e67549af33c3527000000000000000000000000000000000000000000000000000000000000001c7465737431000000000000000000000000000000000000000000000000000000
```

**Comment by aupiff** [comment]
This from `TH.hs` must change since there are array types which are not dynamic.

```haskell
-- | Solidity dynamic type predicate
isDynType :: Text -> Bool
isDynType "bytes"  = True
isDynType "string" = True
isDynType x | T.any (== '[') x = True
            | otherwise        = False
```

**Comment by akru** [comment]
You are absolutely right, but I'm not sure that dynamic list is best representative type for static array.
So, some staff like [sized vectors](https://hackage.haskell.org/package/sized-vector-1.4.3.1/docs/Data-Vector-Sized.html) can be used for this feature.

**Comment by akru** [comment]
So, this issue looks like particular case of #25.
@blinky3713 on your case, can you see broken encoding on static arrays only, or anything else?

**Comment by aupiff** [comment]
Yep, I agree about using something like sized vectors. That library seems to be deprecated, however; the library author now suggests using [Data.Sized](https://hackage.haskell.org/package/sized-0.2.1.1/docs/Data-Sized.html). I'll explore a few options today and try to write a fix.

**Comment by blinky3713** [comment]
I was more referring to how you calculate offsets in general is incorrect. I can try to put together a basic hspec unit test suite based on the purescript web3 test suite, it should almost be as easy as copy paste

**Comment by blinky3713** [comment]
This has more to do with encoding tuples
