### ISSUE TITLE
int* types improperly encoded & decoded

### ISSUE THREAD

**Issue by aupiff** [airalab/hs-web3#28]
Signed types like `int256` should have a separate corresponding Haskell type from `uint`. They must have an `ABIEncoding` instance that properly encodes / decodes two's complement hex strings.

Currently, `-10` will decode as `115792089237316195423570985008687907853269984665640564039457584007913129639926`.

**Comment by akru** [comment]
Thank you for reporting, looks like is needed addition checks [here](https://github.com/airalab/hs-web3/blob/master/src/Network/Ethereum/Web3/Encoding/Internal.hs#L85).
