### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by edevil** [airalab/hs-web3#3]
Could you provide some more usage examples, please?

Specifically something that does not use the DefaultProvider so that we can specify the rpc URI. Does this lib support an IPC path as well?

**Comment by akru** [comment]
Hey!

For example, the real word project usage is
https://github.com/airalab/aira-IoT/blob/master/docker/market-switch/app/Main.hs#L31

No, library support JSON-RPC only, most popular Ethereum nodes provide it.

**Comment by edevil** [comment]
Thanks! That helped.
