### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by kejace** [airalab/hs-web3#4]
In order to parse the output of `truffle compile`, I had to zoom into the `abi` part of the JSON file. See this PR for details: https://github.com/kejace/hs-web3/pull/1/files
What is the intended input for `quoteAbiDec`?

**Comment by akru** [comment]
The input for `quoteAbiDec` is clean ABI given by `solc`, for example:
https://github.com/airalab/core/blob/master/abi/Owned.json

Your approach can be very useful as option when clean ABI cannot be parsed,
for truffle output, as you show.

**Comment by akru** [comment]
Hi again! Do you want to pull changes to upstream?

**Comment by akru** [comment]
So, I close this, reopen as you need it.
