### ISSUE TITLE
Need to reuse request manager

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#42]
Currently you are creating a new tls manager for every rpc request. 

https://github.com/airalab/hs-web3/blob/master/src/Network/Ethereum/Web3/JsonRpc.hs#L50

This is pretty bad, it's best to share the same manager between requests and between threads if possible as per the library's instructions: 

https://hackage.haskell.org/package/http-client-0.1.0.0/docs/Network-HTTP-Client-Manager.html

One solution to this problem would be to bring a reader monad inside the `Web3` stack that has a uri and manager in its environment. What do you think?

**Comment by akru** [comment]
You absolutely right!

One of the point is use ‘Provider’ related type to control execution flow for http-provider, wrap Manager as reader monad, etc.

I’m not sure than reader with Manager in web3 monad is best solution, but as parameter of this it can be.

In my opinion we need some generalization of Provider type class, like another web3 implementations has HTTPProvider, IPCProvider, etc.

**Comment by blinky3713** [comment]
I'm not sure I understand. Maybe you could give a sketch here of how application code would look for just HttpProvider with your ideal solution?

**Comment by akru** [comment]
So, in my opinion we can incapsulate Json-Rpc communication (over http or ipc) in one module, in this case we don’t need separate IPC calls to module and create different http- and ipc-provider.

According to https://kseo.github.io/posts/2017-01-23-custom-connection-manager-for-http-client.html we can use http-client fo IPC connections too.

In this case we can simple define Web3 as:

newtype Web3 a b = Web3 { unWeb3 :: ReaderT (ServerUri, Manager) IO b }

And use the same Provider for http and ipc calls.

**Comment by akru** [comment]
Implemented in #47
