### ISSUE TITLE
sendTx  undocumented

### ISSUE THREAD

**Issue by termslang** [airalab/hs-web3#43]
No reliable documentation how you submit a transaction

**Comment by akru** [comment]
Hi!
As you can see here: http://hackage.haskell.org/package/web3-0.6.0.0/docs/Network-Ethereum-Web3-Contract.html

sendTx accept address, value and abi-encodable entity to send transaction. Transaction encoded and send by JSON-RPC ‘eth_sendTransaction’.

**Comment by akru** [comment]
If you have any questions you are free for reopen.

**Comment by termslang** [comment]
Managed to send a transaction like this:
  let token = "0x4D32DECe5810e15164c36E91d62cE6B16Df4F747"
      to = "0xEb2e0C8e6E2D596ab4C15A1d4Ec16a54c98559c9"
  Right s <- runWeb3 $ return . show =<< transfer token nopay to 100

Now I'm trying to find a way to send data to address 0x00 and I can't find any good example

**Comment by akru** [comment]
For this purpose in `hs-web3-0.6.*` you can use, for example, instance of ABI encoding like this:
MyContract
```haskell
data MyContract = MyContract

instance Method MyContract where
  selector = const "0x"

instance ABIEncoding MyContract where
  fromDataParser = undefined
  toDataBuilder = const "cafecafe"

main = do
  tx <- runWeb3 $ sendTx to nopay MyContract
  print tx
```

where `MyContract` is data object of your deployed contract, and instance of `ABIEncoding` define contract bytecode (`"cafecafe"`).

**Comment by termslang** [comment]
‘selector’ is not a (visible) method of class ‘Method’

**Comment by akru** [comment]
Oops, my mistake, I fix the sample

**Comment by termslang** [comment]
I'm doing it this way and I'm not getting my contract deployed:

data MyContract = MyContract
instance Method MyContract 
instance ABIEncoding MyContract where
  fromDataParser = undefined
  toDataBuilder = const "0x7fe1fffcc..."
main :: IO ()
main = do
  let to = "0x0000000000000000000000000000000000000000"
  tx <- runWeb3 $ sendTx to nopay MyContract
  print tx


https://ropsten.etherscan.io/tx/0xb6dd4ea168ab54f332a5ba594b414f802f43d471babeab23a22875b8850a52ed

Here is another transaction deploying the same bytecode:
https://ropsten.etherscan.io/tx/0x650ad7040553764bcaad3bce62da8680c9845ec6e93fef411c8d4d625b3371b2

I must misunderstand mechanics of the whole thing, but all I want is to deploy a contract and test its methods, the way I do in web3.js

**Comment by akru** [comment]
Currently hs-web3 have no method to create new contract like `contract.new` in web3js. You can use raw eth_sendTransaction from `Network.Ethereum.Web3.Eth` module.

So, also you can create proposal(in issue) to add `new` method for contract deploying in pairing with [hs-web3-solidity](https://github.com/airalab/hs-web3-solidity) library for contract compiling.
