### ISSUE TITLE
can't add web3 as dependency

### ISSUE THREAD

**Issue by zhangchiqing** [airalab/hs-web3#45]
I have the following environment:
```
▸ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0

▸ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library

▸ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1
```

I created a new project with `stack new testweb3`, and added `web3` as dependency in `package.yaml` like this:
```
dependencies:
- base >= 4.7 && < 5
- web3
```

And when I ran `stack build`, I got the following error:
```
▸ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for testweb3-0.1.0.0:
    web3 must match -any, but the stack configuration has no specified version (latest matching version is 0.6.0.0)
needed since testweb3 is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps in /Users/leo/zhangchiqing/testweb3/stack.yaml:

- web3-0.6.0.0

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * You may also want to try using the 'stack solver' command.

Plan construction failed.
```

**Comment by aupiff** [comment]
@zhangchiqing you have to follow the instructions given in the error message, namely to specify a version number in `extra-deps` or `dependencies` (you probably should be using `extra-deps`). The version available on hackage right now is quite old. I recommend that you point to a recent git hash in your `package.yaml` or `stack.yaml` in the `packages` list.

@akru I see on hackage that the latest package update was `Tue Nov 14 12:52:27 UTC 2017 by akru`. Can you please update the package on hackage?

**Comment by akru** [comment]
@aupiff Currently I prepare release with lots of changes and of course upload it to hackage as it’ll finish.

**Comment by akru** [comment]
Hello @zhangchiqing, I glad to say than new hs-web3 release should solve this issue.
Also I waiting for stackage to add web3 to stack nightly and LTS.
