### ISSUE TITLE
Can't get events to work for basic contract

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#5]
First of all, this library is amazing, but I'm having a few errors when getting started. I have the following extremely simple contract 

```js
contract SimpleStorage {

  uint public count;

  event CountSet(uint indexed newCount);

  function setCount(uint _count) {
    count = _count;
    CountSet(_count);
  }

}
```
I followed some of [your examples](https://github.com/airalab/aira-IoT/blob/master/docker/market-switch/app/Main.hs) and created the following code to just print all the incoming events to the console.

```haskell
[abiFrom|abi/SimpleStorage.json|]


data Geth
instance Provider Geth where
    rpcUri = return "http://localhost:8545"

countMonitor :: Address -> Web3 Geth (Chan CountSet)
countMonitor storageAddress = do
  c <- liftIO newChan
  event storageAddress $ \e -> do
    liftIO $ writeChan c e
    return ContinueEvent
  return c

storedPrinter :: Chan CountSet -> IO ()
storedPrinter c = do
  (CountSet val) <- readChan c
  print $ "The the stored value is now: " <> show val

printEvents :: IO ()
printEvents = do
  storageAddress <- fromString <$> getEnv "STORAGE_ADDRESS"
  countUpdateChan <- runWeb3' $ countMonitor storageAddress
  case countUpdateChan of
    Left e  -> print $ "Coudn't start the count channel: " <> show e
    Right c -> storedPrinter c
```

However, when I launch the application, I get one of two different kinds of errors
```
start-app: JsonRpcFail (RpcError {errCode = -32000, errMessage = "filter not found", errData = Nothing})
start-app: thread blocked indefinitely in an MVar operation
```
or
```
start-app: Data.Text.Lazy.Builder.Int.hexadecimal: applied to negative number
CallStack (from HasCallStack):
  error, called at ./Data/Text/Lazy/Builder/Int.hs:176:19 in text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR:Data.Text.Lazy.Builder.Int
start-app: thread blocked indefinitely in an MVar operation
```
Is this something which is wrong with the library, or something that I'm not understanding correctly?

**Comment by blinky3713** [comment]
I should also mention that I am able to successfully change the state of this contract and produce events, and that the contract address I am passing as an environment variable is correct.

**Comment by martyall** [comment]
1.6

**Comment by blinky3713** [comment]
yes, it's 1.6

**Comment by blinky3713** [comment]
I figured out the problem. Geth stopped using increasing natural numbers for it's filter ids and started using some other kind of random hex string [see here](https://github.com/ethereum/go-ethereum/blob/release/1.6/rpc/utils.go#L239). This caused the underlying `Int` in `FilterId` to overflow, leading to either negative filter id's, or nonexistent ones. The problem is fixed if you change `FilterId` to wrap `Integer`, and this seems like it doesn't affect parity providers either. Would you be willing to change this?

**Comment by akru** [comment]
So, can you test the fixed version with geth?

**Comment by blinky3713** [comment]
Yes I can verify that this works together with the changes I'm submitting for #6
