### ISSUE TITLE
Runtime specification of providers

### ISSUE THREAD

**Issue by cies** [airalab/hs-web3#52]
First: thanks for open source'ing this lib!

Now I'd like to specify a provider at runtime, but it does not seems to accept that since providers need to be instances of `Provider`, which is a compile time thing (right?).

What would be a good place to hook into the internals of the lib to accomplish this? Or would it be possible to expose a function that allows me to specify a provide at runtime?

Cheers.

**Comment by akru** [comment]
Tiny JSON-RPC client will be open in future release.

About Provider - it’s not fully truth, currently, Provider is a data type and fields of this you can read in runtime as you needed. You can read Provider via IO and pass it to runWeb3 function, for example.

**Comment by cies** [comment]
> Tiny JSON-RPC client will be open in future release.

You mean to split it out of Web3?

> About Provider - it’s not fully truth, currently, Provider is a data  type and fields of this you can read in runtime as you needed. You can  read Provider via IO and pass it to runWeb3 function, for example.

I understood that I can read `Provider`s as runtime, but I'd like to specifically create them at runtime. AFAIK that is not possible.

For now I've forked the code base and made `JsonRpc` visible. I rather collaborate on a piece of code like this then create an alternative lib. When I add functionality that makes sense to include in `web3` I will discuss it there. (btw I really like the latest changes in in the lib, especially moving away from the 0x Text everywhere approach).

**Comment by cies** [comment]
For sake of completeness: https://github.com/cies/hs-web3/commit/71b2af6fc410628ad5b8deeb8ce6f7b872f821b9

**Comment by akru** [comment]
I'm not sure that one-file library currently is a good idea, tiny JSON-RPC client implementation is independent now but I like to use it in bundle of web3.

Can you explain use cases for Provider creation in runtime? In code, for example, as you like to see it in library.

**Comment by cies** [comment]
Sure. I want to use a config file to specify several nodes (some geth some
parity) and have my program manage them (check health, possibly
adding/removing nodes at runtime) and act as a single point of interaction
with all of them.

**Comment by akru** [comment]
As I see you need some kind of providers pool and abstraction for using it as single Provider, right?

**Comment by akru** [comment]
@cies, as you can see in new release JSON-RPC client are separated. Can you explain what you want to do in this issue?
