### ISSUE TITLE
Reason for "nonce" not to be in the Call record?

### ISSUE THREAD

**Issue by cies** [airalab/hs-web3#53]
I found "none" missing in the `Call` record (used by `sendTransaction`). Is there a reason for this, could just be there as a `Maybe Text` I suppose...

**Comment by akru** [comment]
Yes, you absolutely right, it can be added according to specification: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

**Comment by aupiff** [comment]
I'll add this in the PR I'm working on to enable offnode signing. In my current implementation I'm passing nonce as an additional parameter to a `createRawTransaction` function but that is clearly not ideal.

**Comment by aupiff** [comment]
@akru you fixed this in commit afcb8cc8536ed042378e263ffc6595223c3fface, you can close this.

**Comment by akru** [comment]
Yes, thank you @aupiff!
