### ISSUE TITLE
Geth's types or "our" types?

### ISSUE THREAD

**Issue by cies** [airalab/hs-web3#55]
Sorry for bothering you once again (3rd ticket in a short while, but also ticked one TODO off with a PR :tada: )...

This issue I'm raising is a bit of a philosophical one. Currently the types that are defined in hs-web3 are a bit of a mix of the "logical" types, and the Geth's types.

For instance geth defined QUANTITY, and can sometimes be 0x0 with special meaning or null with special meaning. Should be create a type Quantity? Should it be like Geth's, so having 0x0 with special meaning and the ability to null it? Or should be use a Maybe container for those cases (there by making "our" Quantity different from Geth's QUANTITY?

Similarly for other times. Geth uses 0x-timestamps. Should hs-web3 follow suit? Or should we convert to the more "logical" UTCTime? Or even meet in the middle with POSIXTime?

What I often find in libs is that there is a low level lib, basically following the types of the system it sits on top of, and a higher level lib that uses the types that are closer to what are commonly used in Haskell.

I think it would a good idea to take a stance on this in hs-web3, not to change things radically, but more as to what the lib aspires to be. Just my thoughts though, feel free to ignore. Very interested in a response for the authors. Maybe (probably) I overlooked some things.

**Comment by akru** [comment]
It’s really very interested question! And it have some correlation with #15.

In my opinion in library we have two interfaces: low-level is a raw projection of generic json-rpc interface of ethereum node, and high level is a contract abstraction.

In my opinion, json-rpc should be equal to specification as possible, and high level contract interface should be equal to contact ABI types as possible. But it doesn’t mean that this types should haven’t support traditional Haskell type classes like Integral or Num for UIntN type. In my opinion we should have simple way to coerce Web3 types to traditional Haskell types, but should care about type safety.
