### ISSUE TITLE
`abiFrom` can produce illegal variable names

### ISSUE THREAD

**Issue by aherrmann** [airalab/hs-web3#57]
`abiFrom` produces invalid Template Haskell splices when the contract has methods whose name is a Haskell keyword (`import`, `let`, `module`, `where`, ...) causing an "Illegal variable name" error "when splicing a TH declaration".
Would it be possible to escape such names, or allow the caller to pass in a renaming function?

**Comment by akru** [comment]
Yes, you are right, as I see currently generated names have no escape checks. But it is sensitive trouble for contract method helpers  only, because all variables generated randomly via ‘newName’ and type names are not affected.

I’ll add method name escaping in future releases.

**Comment by akru** [comment]
Implemented in v0.7.1.0

**Comment by aherrmann** [comment]
@akru Thanks for resolving this issue so quickly.
