### ISSUE TITLE
Event topic formatting is not really correct.

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#6]
take the following example contract

```js
contract SimpleStorage {

  uint public count;

  event CountSet(uint newCount);

  function setCount(uint _count) {
    count = _count;
    CountSet(_count);
  }
}
```

the splice dump for the generated `Event` instance is

```haskell
    instance Event CountSet where
      eventFilter _ a
        = Network.Ethereum.Web3.Types.Filter
            (Just a)
            (Just
               [Just
                  "0xa32bc18230dd172221ac5c4821a5f1f1a831f27b1396d244cdd891c58f132435",
                Nothing])
            Nothing
            Nothing
```

This is in incorrect for geth, and I presume parity as well because of [this](http://solidity.readthedocs.io/en/develop/abi-spec.html#events). The problem is that the topic ` [Just "0xa32bc18230dd172221ac5c4821a5f1f1a831f27b1396d244cdd891c58f132435", Nothing]` serializes to 

```json
["0xa32bc18230dd172221ac5c4821a5f1f1a831f27b1396d244cdd891c58f132435", null]
```
indicating that there is an indexed value being watched for, though we don't care what it actually is. However, the topic that is written to for `CountSet` is just 
```json
["0xa32bc18230dd172221ac5c4821a5f1f1a831f27b1396d244cdd891c58f132435"]
```
 since there are not indexed arguments. I have verified that for geth, if you change your definition of [`eventFilterD`](https://github.com/airalab/hs-web3/blob/master/src/Network/Ethereum/Web3/TH.hs#L176) to drop this extra `Nothing`, then the `CountSet` event is caught as expected.

This seems to indicate that your TH should probably pass the number of indexed args in the event to `eventFilterD`, then use `replicate` to place the appropriate number of `Nothings`. Can I make a pull request?

**Comment by akru** [comment]
Hi! Thank you for the great work!

Waiting for the pull request of this.
