### ISSUE TITLE
Deploy contract from hs-web3

### ISSUE THREAD

**Issue by aherrmann** [airalab/hs-web3#62]
Would it be possible to add functionality to deploy contracts from within `hs-web3`?

I found [this StackExchange post](https://ethereum.stackexchange.com/questions/10862/deploying-contract-with-constructor-arguments-via-geth-rpc) quite helpful in figuring out the necessary steps.

I haven't thoroughly tested the deployed contracts, but the following steps seem to be working on parity v.1.9.5 (the `--logging=info,rpc=trace,own_tx=trace` flag was very helpful for debugging).

Here is how to deploy a contract without any constructor arguments:

``` haskell
-- | Binary contract, assuming that its hex representation is stored in @path/to/contract.bin@.
contractBin :: Bytes
contractBin = either error id $
  convertFromBase Base16 $(embedFile "path/to/contract.bin")

deploy :: Call -> Web3 Address
deploy call' = do
  tx <- sendTransaction call' { callData = Just contract, callValue = Nothing }
  mbAddress <- (receiptContractAddress =<<) <$> getTransactionReceipt tx
  maybe (error "failed to deploy contract") return mbAddress

-- Call as
-- @
--   deploy def { callFrom = Just deployer, callGas = Just someGas }
-- @
```

And here is how to deploy a contract with constructor arguments:

``` haskell
contractBin :: Bytes
contractBin = either error id $
  convertFromBase Base16 $(embedFile "path/to/contract.bin")

data Constructor = Constructor [Address] (UIntN 256) (UIntN 256)
  deriving Generic
instance Generics.SOP.Universe.Generic Constructor
instance ABIGet Constructor
instance ABIPut Constructor
instance ABIType Constructor where
  isDynamic = const False
instance Method Constructor where
  selector = mempty

deploy :: Call -> [Address] -> UIntN 256 -> UIntN 256 -> Web3 Address
deploy call' arg1 arg2 arg3 = do
  tx <- sendTransaction call'
    { callData = Just $ contract <> encode (Constructor arg1 arg2 arg3)
    , callValue = Nothing }
  mbAddress <- (receiptContractAddress =<<) <$> getTransactionReceipt tx
  maybe (error "failed to deploy contract") return mbAddress

-- Call as
-- @
--   deploy def { callFrom = Just deployer, callGas = Just someGas } arg1 arg2 arg3
-- @
```

I've confirmed with `getCode` that code was deployed to the chain, and called some simple functions on the contracts which responded with the correct expected results.

The constructor signature is already being parsed from the ABI definition. Maybe `abiFrom` could generate an additional function, say `constructor :: Call -> Bytes -> Arg1 -> Arg2 -> Web3 Hash` that takes the binary contract and constructor arguments (if applicable) and deploys the contract?

**Comment by akru** [comment]
Hello @aherrmann! 
Yes, I already keep in mind contract deployment feature for hs-web3 long time.
In my vision it can be implemented in pair with [hs-web3-solidity](https://github.com/airalab/hs-web3-solidity).

In my opinion, implementation consist of two phases:
1. Contract deployment function in Ethereum.Contract.Method (deployed contract address tracker)
2. TH generator for contract deployment helper (from ABI constructor definition)
3. (optional) use hs-web3-solidity to get bytecode/abi from sources on TH state.
