### ISSUE TITLE
This library's types are getting harder and harder to use in practical applications

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#69]
It seems like the types are getting more and more bound to the EVM and it makes this library a pain to use. For example, now `Address` is `UIntN 160` and there's no functions like 

```haskell
parseAddress :: Text -> Either String Address
```

only the `fromString` method which throws an exception if it fails. These kinds of things used to be there, but for some reason you've taken them out. Now in order to make an address I need to import some low level bytestring library and `DataText.Encoding`. This is apparently also going to be the case for `Hash` now.

I don't really understand why these changes are bubbling up so high, the web3 api clearly has two different kinds of types: hex encoded integers and hex encoded bytestrings. I'm all for fine grained control over the kinds of types one submits in transactions or gets back in event logs, but there's no reason for the web3 api interface to be so complicated.

**Comment by akru** [comment]
It's not exactly truth, both a `Address` and a `Bytes` types have `FromJSON` instances and you can use Aeson codecs if you need text conversions like in your example.

The question about types already was in #55 and I can repeat: low level API should be equal to [Generic JSON-RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC) and EVM related types should be equal to EVM specs. It's my vision. Haskell have powerful strong type system and it helps us to prevent lots weak typed mistakes, like in web3js.

I glad to get your feedback. If you have any practical improvements of code and type conversions we can discus it here.

**Comment by blinky3713** [comment]
We're in agreement about the types which support the JSON RPC spec, but that's not really how it's being implemented. Your Web3.Types module is dependent on the EVM types. eg.

```haskell
Hash ~ BytesN 32
Address ~ BytesN 160
data Change = {
  ...
 , changeTopics           :: ![BytesN 32]
 ...
}
```

Concretely I have another Haskell stream processing service consuming input from this library, and none of these types can be operated on without wrapping or converting them. It also just seems  like the dependencies are inverted, the web3 api shouldn't have to care about what types exist in the EVM. The analogy here is that changing your database schema shouldn't break your api -- your code should separate those concerns for you.

I'm also sort of venting because many of these changes didn't go through PR, they were simply mentioned in issues but then there was never a chance to discuss the code because it was simply merged. The team at FOAM has contributed the vast majority of the improvements / fixes to this library in the last 6 months, but we're not being consulted about any of these directions through PRs which I think is unfair.

**Comment by akru** [comment]
Yes, FOAM team made a great contribution for the library, thank you.

Some words about databases.
Your analogy is not exactly complete and I see here big differences in our visions, you say that JSON-RPC API is an abstraction above a database schema, like ORM maybe, BUT JSON-RPC API is very low-level, it's ethereum node interaction interface, it's more looks like SQL. Low-level api may be changed from one release to another, right? Maybe we need to make more abstract and high-level interface, more stable and more haskell type frendly?

Now high-level is smart-contract interaction and event listening, but here is important to follow EVM types for security reasons.

Some word about discussions.
We are open for discussions at all time. If you want to discuss anything you can write an issue, like you do now. But as a maintainer I have a right to control library evolution bounds in my vision.
