### ISSUE TITLE
Unsigned integer bounds and overflow

### ISSUE THREAD

**Issue by aherrmann** [airalab/hs-web3#72]
I noticed a few issues with the unsigned integer type `UIntN`.

- `maxBound :: UIntN 256` is too small.
    ```
    >>> (2^(256::Int) - 1) - fromIntegral (maxBound :: UIntN 256) :: Integer
    1
    ```
    The reason is that `maxBound :: UIntN 256` is effectively implemented as `2^256 - 1 :: UIntN 256`.
    The `2^256` will overflow leading to `0 - 1`. The subtraction uses the implementation of the underlying `Word256` from basement, which (surprisingly) seems to be using one's complement instead of two's complement. `complement 0 :: UIntN 256` produces the correct upper bound.

- Overflow exceeds bounds for `UIntN n` with `n < 256`.
    ```
    >>> maxBound + 1 :: UIntN 8
    256  -- should be 0
    >>> 0 - 1 :: UIntN 8
    115792089237316195423570985008687907853269984665640564039457584007913129639934  -- should be 255
    ```
    I cannot actually find a part of the Solidity spec that explicitly specifies the expected results in these cases. However, both Parity and [Remix's](https://remix.ethereum.org) JavaScript VM agree that the above outcome is wrong, as can be tested with the following Solidity contract.

```
pragma solidity ^0.4.21;

contract TEST {
    function test256() public pure returns (uint256 result) {
        uint256 a = 0;
        uint256 b = 1;
        /* returns 115792089237316195423570985008687907853269984665640564039457584007913129639935 */
        return a - b;
    }
    function test128() public pure returns (uint128 result) {
        uint128 a = 0;
        uint128 b = 1;
        /* returns 340282366920938463463374607431768211455 */
        return a - b;
    }
    function test64() public pure returns (uint64 result) {
        uint64 a = 0;
        uint64 b = 1;
        /* returns 18446744073709551615 */
        return a - b;
    }
    function test32() public pure returns (uint32 result) {
        uint32 a = 0;
        uint32 b = 1;
        /* returns 4294967295 */
        return a - b;
    }
    function test16() public pure returns (uint16 result) {
        uint16 a = 0;
        uint16 b = 1;
        /* returns 65535 */
        return a - b;
    }
    function test8() public pure returns (uint8 result) {
        uint8 a = 0;
        uint8 b = 1;
        /* returns 255 */
        return a - b;
    }
}
```

**Comment by akru** [comment]
Hi @aherrmann thank you for reporting! Do you have any ideas how to fix it?

**Comment by aherrmann** [comment]
@akru I've opened a PR (https://github.com/haskell-foundation/foundation/pull/498) with foundation. That one should fix the subtraction and `maxBound`.

Wrt over/underflow on smaller width unsigned integers, a simple solution might be to always mask the bits after operations that could over/underflow. E.g. something like

```
UIntN a + UIntN b = mask $ UIntN (a + b)

mask :: UIntN n -> UIntN n
mask = (maxBound .&.)
```
