### ISSUE TITLE
Code does not sync with Hackage and Stackage's documents

### ISSUE THREAD

**Issue by locosoft1986** [airalab/hs-web3#75]
The current source code api does not sync with Hackage and Stackage's documents. It seems like the documents is at tag 0.7.3.0.  I have to install web3 dependency from git repo directly.

**Comment by akru** [comment]
Yes your are absolutely right, because master branch is not fixed to latest release, it looks like a future release and in some time I fork master branch for specified release version - a tag.

**Comment by locosoft1986** [comment]
when I use the following code in the GHCI to connect with my Ganache local test net:
`
import Network.Ethereum.Web3.Provider
import Network.Ethereum.Web3

localNode = Provider (HttpProvider "http://localhost:7545") Nothing

result = runWeb3' localNode clientVersion
`

and type "result" then hit enter to show the value, I got:
`
*** Exception: ParsingException "Error in $: Failed reading: not a valid json value"
`

I also tried to use `runWeb3 clientVersion` directly but I got same exception.
