### ISSUE TITLE
Can't connect to infura

### ISSUE THREAD

**Issue by zhangchiqing** [airalab/hs-web3#76]
I'm trying to connect to infura and get the gas Price with the following request. (The API key is removed)
```
runWeb3' (HttpProvider "https://mainnet.infura.io/<API_KEY>") gasPrice
```

But I got the following exception: (The path is showing the API_KEY, I removed it, but you can reproduce by using your own key)
```
*** Exception: HttpExceptionRequest Request {
  host                 = "mainnet.infura.io"
  port                 = 443
  secure               = True
  requestHeaders       = [("Content-Type","application/json")]
  path                 = "/<API_KEY>"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 TlsNotSupported
```

Stackage version: lts-11.16

Do I miss anything?

**Comment by akru** [comment]
HTTPS connections are use TLS and it is disabled by defaul in hs-web3. try to build web3 with ‘tls’ flag 
https://www.haskell.org/cabal/users-guide/installing-packages.html#controlling-flag-assignments
https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#flags

**Comment by zhangchiqing** [comment]
Is it possible to support TLS by default in the future? 

Infura is a common choice for connecting to a geth node, and their JSONRPC API only supports HTTPS.

**Comment by zhangchiqing** [comment]
Adding the following code in `stack.yaml` worked. Thanks @akru. 
```
flags:
  web3:
    tls: true
```
