### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#8]
It would be good to get some unit testing, something like what web3js does in their pre-1.0 testing using the `FakeHttpProvider` just to verify correct formatting of types, transactions, event topics, etc. I understand how this is not really needed as badly as it would be for them, but still I think it would be better to have them. Would you be open to a pr in this direction?

**Comment by akru** [comment]
Yes, you are absolutely right, glad to hear this!
What unittest package you want to use?

**Comment by aupiff** [comment]
What do you think about writing both `geth` and `parity` automated tests? I think we should have a test truffle project whose contracts can be deployed to a local blockchain. This way we can test the TH abi code as well as all the JSON RPC methods.

I currently do `geth` testing by using a bash script like this which calls `truffle migrate`: https://github.com/blockmason/friend-in-debt/blob/master/ucac/gethtest.sh#L71

**Comment by akru** [comment]
Yes, for testing truffle project can be added to `tests` directory.

In my opinion a good way to start is simple tests like `Eth.getBalance`, but I'm not sure about `geth` in Travis environment. So, we can use Travis cache to store chain.

Also ethereum-testrpc can be used for tests on a par with geth and parity clients.

**Comment by blinky3713** [comment]
Our experience at Foam has been to avoid the combination of truffle with testrpc, because truffle is bundled with the solidity-js compiler which is often incompatible with the vm running in testrpc. Instead we opt to use a specialized, ephemeral docker container running a lightweight and fast geth client during testing. If you are interested in exploring this route, our devops engineer @iostat can explain a possible setup for your ci jobs. I'm sure we can replicate the same thing with parity.

**Comment by blinky3713** [comment]
That being said, I think the encoding tests should ideally be run against a set of known, correct encodings rather than depending on an live node. It simplifies the situation to what is actually needed. We're developing a purescript-web3 library which is a faithful porting of hs-web3 to purescript which takes this approach based on some stolen examples from web3js and the solidity documentation.

**Comment by aupiff** [comment]
@blinky3713 yes, please do invite me to view your purescript libraries.

I agree with you about the encoding tests.

**Comment by blinky3713** [comment]
@aupiff just sent you an invite for purescript-web3 (the core library) and purescript-web3-generator (plays the role of TH quasiquoter here for automatic code generation from abi)

**Comment by aupiff** [comment]
@blinky3713 I'm surprised at this comment you made:
```Our experience at Foam has been to avoid the combination of truffle with testrpc, because truffle is bundled with the solidity-js compiler which is often incompatible with the vm running in testrpc. ```

Can that be true? Most of the testing I do involves testrpc and truffle and I've never had trouble with that combination. The `solidity-js` compiler IS the c++ solidity compiler whose LLVM bytecode is converted to JS using emscripten. I doubt there are any differences in the resultant solidity bytecode.

**Comment by blinky3713** [comment]
I can definitely attest to have had invalid op code errors thrown by testrpc on compiled solidity code that is tested with an isolated dockerized geth 6.7 node, by hand on remix, and that pass on the test networks. Our opinion is that testrpc serves no real purpose if you can run an ephemeral dockerized geth or parity single-node that is currently being used on the live net and has consistent block times under 3 seconds.

**Comment by aupiff** [comment]
@blinky3713 Mmm, I' be curious to investigate that further. I believe what you say, but I'd love to see an example of such bytecode. `testrpc` is very useful to me during development.

`testrpc` is easier to setup than a dockerized `geth` node, and runs much faster. I can run a whole testsuite involving many transactions in 3 seconds; if I had to wait for 3 second blocks, initial startup, account creation & unlocking, my tests would take at least a few minutes. I think the ethereum community has a lot to gain by maintaining projects like `testrpc`. As a side project and pedagogical exercise, I'd love to work on a `testrpc` clone in Haskell.

That said, I'd love to see your test setup; perhaps my `geth` testing could be made much faster somehow.

**Comment by akru** [comment]
Tuple encoding tests bench is needed for #25,
as I can see, @blinky3713 use testing framework looks like [hspec](https://hackage.haskell.org/package/hspec).

**Comment by blinky3713** [comment]
yeah, you could probably almost copy and paste [those tests](https://github.com/f-o-a-m/purescript-web3/blob/master/test/Web3Spec/Encoding/Containers.purs)

**Comment by akru** [comment]
@blinky3713 Is you work on tests complete?

**Comment by blinky3713** [comment]
Well I think that this issue is definitely closed. If we wanted more specific tests, we should start a separate issue?

**Comment by akru** [comment]
Yes, foundation is created.
