### ISSUE TITLE
Gas estimation is called even when gas limit is explicitly set

### ISSUE THREAD

**Issue by romankarl** [airalab/hs-web3#89]
If I've seen it correctly, there is a new feature in version 0.8.x to estimate the gas consumption of a transaction before submitting it. Setting the gas limit explicitly doesn't change this behaviour. This seems to be undesired, as a gas estimation for a valid transaction can fail in some cases, and thus preventing the execution of the transaction altogether.

**Comment by akru** [comment]
Thank you for reporting! You are absolutely right, gas estimation should be disabled when gas limit already set. I’ll check and fix it ASAP.
