### ISSUE TITLE
Why are you not reusing the request manager

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#95]
We made this PR a long time ago https://github.com/airalab/hs-web3/pull/47, the whole point was to avoid creating a new TLS manager on every runWeb3 call. Now I'm looking at source code on hackage and I'm finding that 

```haskell

-- | 'Web3' monad runner, using the supplied Manager
runWeb3With :: MonadIO m
            => Manager
            -> Provider
            -> Web3 a
            -> m (Either Web3Error a)
runWeb3With manager provider f =
    runWeb3' provider $ jsonRpcManager .= manager >> f

-- | 'Web3' monad runner
runWeb3' :: MonadIO m
         => Provider
         -> Web3 a
         -> m (Either Web3Error a)
runWeb3' (HttpProvider uri) f = do
    cfg <- defaultSettings uri
    liftIO . try . flip evalStateT cfg . unWeb3 $ f

...

-- | Create default 'JsonRpcClient' settings.
defaultSettings :: MonadIO m
                => String           -- ^ JSON-RPC server URI
                -> m JsonRpcClient
defaultSettings srv = liftIO $ JsonRpcClient
  <$> newManager tlsManagerSettings
  <*> pure srv

```

I would like to point out that creeating a new TLS manager is needlessly expensive, which is the original reason for the first PR. There are two possibilities here

(1) laziness doesn't actually cause `defaultSettings` to run
(2) It does run and this means that every time I make a web3 call I create a new TLS manager, then throw it away, and there's no option to avoid this. 

If it's option (2), I'm completely dumbfounded and cannot understand why you would do this.
If it's option (1), I'm still dumbfounded, and I think it should be changed to not rely on compiler tricks so that it's clear to everyone what's happening here.

**Comment by akru** [comment]
Hello @blinky3713,
I think it’s a good point! Thank you, it could be fixed next release.

**Comment by akru** [comment]
Hello, @blinky3713! I'm sorry for late response.

As I can see the reason why `Manager` created in any response is lazy fields in [JsonRpcClient](https://github.com/airalab/hs-web3/blob/master/src/Network/JsonRpc/TinyClient.hs#L91) data type, right? Probably making this fields strict could fix this issue.
