### ISSUE TITLE
ABI parser: don't require "constant" and "payable" fields, rely on "stateMutability" instead

### ISSUE THREAD

**Issue by enolan** [airalab/hs-web3#98]
As of [Solidity 0.5.0](https://solidity.readthedocs.io/en/develop/050-breaking-changes.html#command-line-and-json-interfaces), it doesn't output those fields anymore. Software is supposed to parse `"stateMutability"` instead. So the library can't read ABIs generated by solidity versions more recent than November 2018.

**Comment by blombern** [comment]
Is there any intention to fix this? I'm looking to use this library for a project, but it seems that this bug is the reason I can't generate client code for the Uniwap RouterV2. I'd love to help but unfortunately, I'm not familiar with Template Haskell or the inner workings of Ethereum (yet).

**Comment by akru** [comment]
Hello @blombern, if no one apply this, I’ll fix it during a week or two in coming release. Thank you for using the library.

**Comment by alexfmpe** [comment]
FWIW `payable` doesn't seem to be required, only `constant`.
Hit this as well and did the simplest change I could to get it working for my use case - https://github.com/obsidiansystems/hs-web3/commit/dac02c09595c5aa47d3e124369d2006e41134b96
For backwards compatibility it should also probably fallback to `constant` / `payable` I think?

**Comment by o1lo01ol1o** [comment]
Any update on this?

**Comment by akru** [comment]
@alexfmpe I guess it's not a problem to bump the minimum solidity version to 0.6+, for code safety reasons it also could be reasonable.

@o1lo01ol1o I'm working on the release, I'll glad for any help, for example, PR with changes https://github.com/obsidiansystems/hs-web3/commit/dac02c09595c5aa47d3e124369d2006e41134b96.

**Comment by alexfmpe** [comment]
> PR with changes obsidiansystems@dac02c0.

Not sure I understand. Should I PR the changes in that commit, or should I apply changes to what I have and then PR?

**Comment by alexfmpe** [comment]
On second thought, my question doesn't really make sense
Opened https://github.com/airalab/hs-web3/pull/102

**Comment by akru** [comment]
Great, thank you @alexfmpe! I'll release it as it will be ready to publish. 
As you can see, the library will be splitter to many packages from the next release, probably Ethereum-related staff could be published soon if needed, but in my opinion better to publish the whole library release in the same time.

**Comment by o1lo01ol1o** [comment]
#102 Still lacks backward compat as evinced by the failure to compile the example here: https://github.com/airalab/hs-web3/runs/1561894819.  

Bumping minimum solidity to 0.6 might be a bit premature as, eg, Uniswap appears to publish some factory abi specs using an earlier verion.

**Comment by akru** [comment]
I see, in that case is better to provide some way to use old solidity abi.

**Comment by alexfmpe** [comment]
Fallback to old parsing if `stateMutability` isn't present then?

**Comment by akru** [comment]
Yes, it looks reasonable. Or using the special function name for importing legacy solidity ABI versions.

**Comment by alexfmpe** [comment]
See #103
